# Required: The name of your Django project
project_name: new

# Optional: Configure the core Django files location
core:
  location: root
  path: core

# Optional: Define directories
directories: []

# Optional: Define apps and their directories
apps:
- directory: ''
  name: accounts

# Optional: Define services and their options
services: []

# Optional: Environment setting (used in settings/__init__.py)
env: dev
